### ISSUE TITLE
schema() raises 404 Error

### ISSUE THREAD

**Issue by poddus** [saphetor/varsome-api-client-python#4]
additionally, requesting `10190091015942290001` as per the [api examples](https://api.varsome.com/) raises 404

```
Python 3.6.4 |Anaconda, Inc.| (default, Dec 21 2017, 15:39:08) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from variantapi.client import VariantAPIClient
>>> 
>>> with open('./varsome_api_key', 'r') as f:
...     key = f.read()
... 
>>> varsome_api = VariantAPIClient(key)
>>> 
>>> varsome_api.schema()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./variantapi/client.py", line 95, in schema
    return self.get(self.schema_lookup_path)
  File "./variantapi/client.py", line 77, in get
    response = self._make_request(path, "GET", params=params)
  File "./variantapi/client.py", line 65, in _make_request
    if r.headers['Content-Type'] == "application/json" else None)
variantapi.client.VariantApiException: 404 (Not Found: either you're requesting an invalid URI or the resource in question doesn't exist)
>>> 
>>> varsome_api.lookup('10190091015942290001')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./variantapi/client.py", line 106, in lookup
    return self.get(self.lookup_path % (query, ref_genome), params=params)
  File "./variantapi/client.py", line 77, in get
    response = self._make_request(path, "GET", params=params)
  File "./variantapi/client.py", line 65, in _make_request
    if r.headers['Content-Type'] == "application/json" else None)
variantapi.client.VariantApiException: 404 (Not Found: either you're requesting an invalid URI or the resource in question doesn't exist)
```

**Comment by poddus** [comment]
schema was due to `schema_lookup_path` having a trailing `/`. (`/lookup/schema/`) removing it solves the problem. haven't figured out the other 404 error yet.

**Comment by poddus** [comment]
I believe it has something to do with the reference genome. the client uses default values for the reference genome but ref_genome does not seem to be implemented server side for varsome variant_ids

**Comment by poddus** [comment]
quick fix on [my development branch](https://github.com/poddus/variant-api-client-python/commit/2b2267d6eaf45e92ab8b4540c7c751ca260c07ce)

**Comment by ckopanos** [comment]
Thanks for the comment on this,

both issues have been fixed in our to be released new version of the client.
The issue you are experiencing with 10190091015942290001 is because this is a variant identifier developed by Saphetor which already includes the reference genome as part of the identifier. So the actual lookup is https://api.varsome.com/lookup/10190091015942290001.
This has also been fixed
